// Trade export utilities — Excel (ExcelJS) and CSV
import ExcelJS from 'exceljs';
import { formatINR } from '@/lib/marketTime';

interface ExportTrade {
  symbol: string;
  side?: string;
  price?: number;
  quantity?: number;
  pnl?: number;
  net_pnl?: number;
  traded_at?: string;
  exchange?: string;
}

interface ExportJournalEntry {
  trade_id: string;
  thesis?: string;
  emotion?: string;
  rating?: number;
  notes?: string;
}

const TRADE_COLUMNS = [
  { key: 'symbol', header: 'Symbol', width: 16 },
  { key: 'side', header: 'Side', width: 8 },
  { key: 'quantity', header: 'Qty', width: 10 },
  { key: 'price', header: 'Price', width: 14, format: 'currency' },
  { key: 'pnl', header: 'Gross P&L', width: 14, format: 'currency' },
  { key: 'net_pnl', header: 'Net P&L', width: 14, format: 'currency' },
  { key: 'traded_at', header: 'Date', width: 20, format: 'date' },
  { key: 'exchange', header: 'Exchange', width: 10 },
];

function cellValue(trade: ExportTrade, key: string, format?: string): string | number {
  const val = trade[key as keyof ExportTrade];
  if (val === null || val === undefined) return '';

  switch (format) {
    case 'currency':
      return typeof val === 'number' ? val : '';
    case 'date':
      return typeof val === 'string' ? new Date(val).toLocaleDateString('en-IN') : '';
    default:
      return String(val);
  }
}

/**
 * Generate a formatted Excel workbook with Trades and optional Journal sheets.
 */
export async function generateTradeExcel(
  trades: ExportTrade[],
  journals?: ExportJournalEntry[],
): Promise<Uint8Array> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'BazaarSaar';
  wb.created = new Date();

  // ── Trades Sheet ──
  const ws = wb.addWorksheet('Trades', {
    properties: { tabColor: { argb: '22C55E' } },
  });

  // Header row
  ws.columns = TRADE_COLUMNS.map((col) => ({
    header: col.header,
    key: col.key,
    width: col.width,
  }));

  // Style header
  const headerRow = ws.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF22C55E' },
  };
  headerRow.alignment = { horizontal: 'center' };

  // Data rows
  for (const trade of trades) {
    const row: Record<string, string | number> = {};
    for (const col of TRADE_COLUMNS) {
      row[col.key] = cellValue(trade, col.key, col.format);
    }
    const dataRow = ws.addRow(row);

    // Color P&L cells
    const netPnl = trade.net_pnl || trade.pnl || 0;
    const pnlCell = dataRow.getCell('net_pnl');
    if (netPnl > 0) {
      pnlCell.font = { color: { argb: 'FF22C55E' }, bold: true };
    } else if (netPnl < 0) {
      pnlCell.font = { color: { argb: 'FFEF4444' }, bold: true };
    }
  }

  // Auto-filter
  ws.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: trades.length + 1, column: TRADE_COLUMNS.length },
  };

  // Freeze header
  ws.views = [{ state: 'frozen', ySplit: 1, xSplit: 0 }];

  // ── Summary Sheet ──
  const summarySheet = wb.addWorksheet('Summary', {
    properties: { tabColor: { argb: '3B82F6' } },
  });

  const wins = trades.filter((t) => (t.net_pnl || t.pnl || 0) > 0);
  const losses = trades.filter((t) => (t.net_pnl || t.pnl || 0) < 0);
  const netPnl = trades.reduce((s, t) => s + (t.net_pnl || t.pnl || 0), 0);
  const grossPnl = trades.reduce((s, t) => s + (t.pnl || 0), 0);
  const avgWin = wins.length > 0 ? wins.reduce((s, t) => s + (t.net_pnl || t.pnl || 0), 0) / wins.length : 0;
  const avgLoss = losses.length > 0 ? losses.reduce((s, t) => s + (t.net_pnl || t.pnl || 0), 0) / losses.length : 0;

  const summaryData = [
    ['Metric', 'Value'],
    ['Total Trades', trades.length],
    ['Wins', wins.length],
    ['Losses', losses.length],
    ['Win Rate', `${trades.length > 0 ? ((wins.length / trades.length) * 100).toFixed(1) : 0}%`],
    ['Gross P&L', formatINR(grossPnl)],
    ['Net P&L', formatINR(netPnl)],
    ['Average Win', formatINR(avgWin)],
    ['Average Loss', formatINR(Math.abs(avgLoss))],
    ['Risk/Reward', avgLoss !== 0 ? Math.abs(avgWin / avgLoss).toFixed(2) : '--'],
    ['', ''],
    ['Generated by', 'BazaarSaar (बाज़ारसार)'],
    ['Date', new Date().toLocaleDateString('en-IN')],
    ['Disclaimer', 'Not investment advice. Past performance is not indicative of future results.'],
  ];

  summaryData.forEach((row) => summarySheet.addRow(row));
  summarySheet.getColumn(1).width = 20;
  summarySheet.getColumn(2).width = 25;

  const summaryHeader = summarySheet.getRow(1);
  summaryHeader.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
  summaryHeader.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF3B82F6' },
  };

  // ── Journal Sheet (if journals exist) ──
  if (journals && journals.length > 0) {
    const journalSheet = wb.addWorksheet('Journal', {
      properties: { tabColor: { argb: 'F59E0B' } },
    });

    journalSheet.columns = [
      { header: 'Trade ID', key: 'trade_id', width: 36 },
      { header: 'Thesis', key: 'thesis', width: 40 },
      { header: 'Emotion', key: 'emotion', width: 14 },
      { header: 'Rating', key: 'rating', width: 8 },
      { header: 'Notes', key: 'notes', width: 50 },
    ];

    const jHeader = journalSheet.getRow(1);
    jHeader.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    jHeader.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF59E0B' },
    };

    for (const j of journals) {
      journalSheet.addRow({
        trade_id: j.trade_id,
        thesis: j.thesis || '',
        emotion: j.emotion || '',
        rating: j.rating || '',
        notes: j.notes || '',
      });
    }
  }

  const buffer = await wb.xlsx.writeBuffer();
  return new Uint8Array(buffer);
}

/**
 * Generate CSV string from trades.
 */
export function generateTradeCSV(trades: ExportTrade[]): string {
  const headers = TRADE_COLUMNS.map((c) => c.header).join(',');
  const rows = trades.map((t) =>
    TRADE_COLUMNS.map((col) => {
      const val = cellValue(t, col.key, col.format);
      return typeof val === 'string' && val.includes(',') ? `"${val}"` : val;
    }).join(',')
  );
  return [headers, ...rows].join('\n');
}
