
-- ============================================
-- BAZAARSAAR - DEPRECATED MIGRATION (NO-OP)
-- ============================================
--
-- This file is intentionally left as a NO-OP.
--
-- Why:
-- The original (legacy) schema in this migration included tables like `signals`
-- and `daily_packs`, plus references to “Python workers”. BazaarSaar's final
-- roadmap has strict non-negotiables: no signals, no predictions, no
-- recommendations, no copy/auto trading.
--
-- Keeping this migration executable would create advice-adjacent tables in new
-- environments and increase compliance risk.
--
-- Notes:
-- - Production schema starts at migration 002+ in this repo.
-- - If you previously applied the legacy schema in an older DB, you should
--   remove/clean up legacy tables as part of a controlled migration plan.
