-- ============================================
-- BAZAARSAAR - INITIAL DATABASE SCHEMA
-- ============================================

-- 1. USER PROFILES
CREATE TABLE IF NOT EXISTS user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  persona VARCHAR(20),
  watchlist TEXT[] DEFAULT '{}',
  language VARCHAR(5) DEFAULT 'en',
  daily_pack_time VARCHAR(5) DEFAULT '08:00',
  notifications BOOLEAN DEFAULT true,
  onboarding_completed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own profile" ON user_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON user_profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON user_profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- 2. STOCKS (populated by Python workers)
CREATE TABLE IF NOT EXISTS stocks (
  symbol VARCHAR(20) PRIMARY KEY,
  name VARCHAR(200),
  exchange VARCHAR(5) DEFAULT 'NSE',
  sector VARCHAR(100),
  industry VARCHAR(100),
  ltp DECIMAL(12,2),
  change DECIMAL(12,2),
  change_percent DECIMAL(8,4),
  open DECIMAL(12,2),
  high DECIMAL(12,2),
  low DECIMAL(12,2),
  close DECIMAL(12,2),
  volume BIGINT,
  market_cap DECIMAL(18,2),
  high_52w DECIMAL(12,2),
  low_52w DECIMAL(12,2),
  pe_ratio DECIMAL(10,2),
  pb_ratio DECIMAL(10,2),
  dividend_yield DECIMAL(6,2),
  roe DECIMAL(8,2),
  promoter_holding DECIMAL(6,2),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_stocks_sector ON stocks(sector);
CREATE INDEX idx_stocks_exchange ON stocks(exchange);

-- 3. SIGNALS (generated by Python workers)
CREATE TABLE IF NOT EXISTS signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL REFERENCES stocks(symbol),
  type VARCHAR(30) NOT NULL,
  strength VARCHAR(10) NOT NULL,
  persona VARCHAR(20) NOT NULL,
  headline TEXT NOT NULL,
  explanation TEXT NOT NULL,
  hit_rate DECIMAL(5,2),
  context TEXT,
  triggered_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_signals_persona ON signals(persona);
CREATE INDEX idx_signals_symbol ON signals(symbol);
CREATE INDEX idx_signals_triggered ON signals(triggered_at DESC);

-- 4. DAILY INTELLIGENCE PACKS
CREATE TABLE IF NOT EXISTS daily_packs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date DATE NOT NULL,
  persona VARCHAR(20) NOT NULL,
  market_summary TEXT,
  top_movers JSONB DEFAULT '[]',
  sector_rotation JSONB DEFAULT '{}',
  signal_ids UUID[] DEFAULT '{}',
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(date, persona)
);

-- 5. INDEX DATA
CREATE TABLE IF NOT EXISTS indices (
  symbol VARCHAR(30) PRIMARY KEY,
  name VARCHAR(100),
  value DECIMAL(12,2),
  change DECIMAL(12,2),
  change_percent DECIMAL(8,4),
  advance INT,
  decline INT,
  unchanged INT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. OPTION CHAIN (for Options Trader persona)
CREATE TABLE IF NOT EXISTS option_chain (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(20) NOT NULL,
  expiry_date DATE NOT NULL,
  strike_price DECIMAL(12,2) NOT NULL,
  option_type VARCHAR(2) NOT NULL,
  open_interest BIGINT,
  change_in_oi BIGINT,
  volume BIGINT,
  iv DECIMAL(8,4),
  ltp DECIMAL(12,2),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(symbol, expiry_date, strike_price, option_type)
);

CREATE INDEX idx_option_chain_symbol ON option_chain(symbol);
CREATE INDEX idx_option_chain_expiry ON option_chain(expiry_date);
